// internal/adapters/gorm/gorm_adapter.go
//
// GORM → schema.sql adapter.
//
// Strategy: GORM's AutoMigrate is only safe in development.
// This adapter:
//   1. Runs AutoMigrate against a THROWAWAY local DB (never production).
//   2. Reads the resulting schema via INFORMATION_SCHEMA.
//   3. Emits clean CREATE TABLE SQL that migrate-gen can track going forward.
//
// After the one-time dump, you STOP using AutoMigrate in production and
// let migrate-gen own all future schema changes.
//
// Build tag: //go:build gorm
// This file only compiles when you pass -tags gorm, keeping the core
// engine free of ORM dependencies.

//go:build gorm

package adapter

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/nutcas3/migrate-gen/adapters"
	"github.com/nutcas3/migrate-gen/internal/diff"

	gormpostgres "gorm.io/driver/postgres"
	gormlib "gorm.io/gorm"
)

func init() {
	adapters.Register(&GORMAdapter{})
}

// GORMAdapter implements adapters.Adapter for GORM.
type GORMAdapter struct {
	// Models is populated by the caller before DumpSchema is called.
	// e.g. adapter.Models = []interface{}{&User{}, &Post{}}
	Models []interface{}
}

func (a *GORMAdapter) Name() string { return "gorm" }

// DumpSchema runs AutoMigrate on the given DSN, then reads the resulting
// schema via INFORMATION_SCHEMA and returns CREATE TABLE SQL.
//
// dsn must point to a THROWAWAY database. NEVER point this at production.
func (a *GORMAdapter) DumpSchema(dsn string) (string, error) {
	db, err := gormlib.Open(gormpostgres.Open(dsn), &gormlib.Config{})
	if err != nil {
		return "", fmt.Errorf("gorm open: %w", err)
	}

	// Run AutoMigrate to materialize the struct definitions into the DB
	if err := db.AutoMigrate(a.Models...); err != nil {
		return "", fmt.Errorf("gorm AutoMigrate: %w", err)
	}

	// Get the underlying *sql.DB so we can use our INFORMATION_SCHEMA inspector
	sqlDB, err := db.DB()
	if err != nil {
		return "", fmt.Errorf("get sql.DB: %w", err)
	}

	return dumpToSQL(sqlDB)
}

// ─────────────────────────────────────────────────────────────────
// GORM → SQL conversion notes
// ─────────────────────────────────────────────────────────────────
//
// GORM field tag → SQL mapping (for reference):
//
//   type User struct {
//       ID        uint           `gorm:"primarykey"`
//       Name      string         `gorm:"size:255;not null"`
//       Email     string         `gorm:"uniqueIndex;not null"`
//       Age       int            `gorm:"default:0"`
//       CreatedAt time.Time
//       DeletedAt gorm.DeletedAt `gorm:"index"`
//   }
//
// Becomes:
//
//   CREATE TABLE "users" (
//       "id"         bigserial    NOT NULL,
//       "name"       varchar(255) NOT NULL,
//       "email"      varchar(255) NOT NULL,
//       "age"        int          DEFAULT 0,
//       "created_at" timestamptz,
//       "deleted_at" timestamptz,
//       PRIMARY KEY ("id")
//   );
//   CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email");
//   CREATE INDEX        "idx_users_deleted_at" ON "users" ("deleted_at");

// ─────────────────────────────────────────────────────────────────
// Shared dump logic (used by all adapters)
// ─────────────────────────────────────────────────────────────────

// dumpToSQL reads a live DB via INFORMATION_SCHEMA and emits CREATE TABLE SQL.
// This is the shared implementation used by every adapter.
func dumpToSQL(db *sql.DB) (string, error) {
	schema, err := diff.InspectDB(context.Background(), db)
	if err != nil {
		return "", fmt.Errorf("inspect db: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("-- schema.sql\n")
	sb.WriteString("-- Auto-generated by migrate-gen dump. Edit this file going forward.\n")
	sb.WriteString("-- DO NOT use ORM AutoMigrate in production after this point.\n\n")

	for _, tname := range sortedKeys(schema.Tables) {
		t := schema.Tables[tname]
		var lines []string

		for _, colName := range t.ColOrder {
			col := t.Columns[colName]
			line := fmt.Sprintf("    %s %s", q(colName), col.FullType)
			if !col.IsNullable {
				line += " NOT NULL"
			}
			if col.DefaultValue.Valid {
				line += " DEFAULT " + col.DefaultValue.String
			}
			lines = append(lines, line)
		}

		if len(t.PrimaryKeys) > 0 {
			var pks []string
			for _, pk := range t.PrimaryKeys {
				pks = append(pks, q(pk))
			}
			lines = append(lines, "    PRIMARY KEY ("+strings.Join(pks, ", ")+")")
		}

		for _, fk := range t.ForeignKeys {
			onDelete := ""
			if fk.OnDelete != "" && fk.OnDelete != "NO ACTION" {
				onDelete = " ON DELETE " + fk.OnDelete
			}
			lines = append(lines, fmt.Sprintf(
				"    CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)%s",
				q(fk.ConstraintName), q(fk.Column), q(fk.RefTable), q(fk.RefColumn), onDelete,
			))
		}

		sb.WriteString(fmt.Sprintf("CREATE TABLE %s (\n%s\n);\n\n",
			q(tname), strings.Join(lines, ",\n")))
	}

	for _, idx := range schema.Indexes {
		unique := ""
		if idx.IsUnique {
			unique = "UNIQUE "
		}
		sb.WriteString(fmt.Sprintf("CREATE %sINDEX %s ON %s USING %s (%s);\n",
			unique, q(idx.Name), q(idx.TableName), idx.Method,
			strings.Join(qAll(idx.Columns), ", ")))
	}

	return sb.String(), nil
}

func q(s string) string { return `"` + s + `"` }
func qAll(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = q(s)
	}
	return out
}

func sortedKeys(m map[string]*diff.Table) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	// sort alphabetically — deterministic output
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[i] > keys[j] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	return keys
}
